// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA7XVQpRy4zn5EvtLVd1fZyZezpErg81Yg',
    appId: '1:400577994211:web:110a3fccf4bb69eb0e94d6',
    messagingSenderId: '400577994211',
    projectId: 'study-sprint-9c722',
    authDomain: 'study-sprint-9c722.firebaseapp.com',
    storageBucket: 'study-sprint-9c722.appspot.com',
    measurementId: 'G-48R4WS08KG',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAbqrctJBtH2oGk1Pgk43jmNZ0hWddJ-LY',
    appId: '1:400577994211:android:f5cc7d936b1c85440e94d6',
    messagingSenderId: '400577994211',
    projectId: 'study-sprint-9c722',
    storageBucket: 'study-sprint-9c722.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBHaXIC381H8_11m1_3Wgw4VHiuQe9MEsk',
    appId: '1:400577994211:ios:1efec44c27ad98050e94d6',
    messagingSenderId: '400577994211',
    projectId: 'study-sprint-9c722',
    storageBucket: 'study-sprint-9c722.appspot.com',
    androidClientId: '400577994211-hurogv577abud3ossuv1d53rqf3hqjjq.apps.googleusercontent.com',
    iosClientId: '400577994211-o4q58e5ao92m3nnurdd1j5ah0bp7lvlf.apps.googleusercontent.com',
    iosBundleId: 'com.example.studyscheduler',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBHaXIC381H8_11m1_3Wgw4VHiuQe9MEsk',
    appId: '1:400577994211:ios:1efec44c27ad98050e94d6',
    messagingSenderId: '400577994211',
    projectId: 'study-sprint-9c722',
    storageBucket: 'study-sprint-9c722.appspot.com',
    androidClientId: '400577994211-hurogv577abud3ossuv1d53rqf3hqjjq.apps.googleusercontent.com',
    iosClientId: '400577994211-o4q58e5ao92m3nnurdd1j5ah0bp7lvlf.apps.googleusercontent.com',
    iosBundleId: 'com.example.studyscheduler',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA7XVQpRy4zn5EvtLVd1fZyZezpErg81Yg',
    appId: '1:400577994211:web:1279fa37af08ffd70e94d6',
    messagingSenderId: '400577994211',
    projectId: 'study-sprint-9c722',
    authDomain: 'study-sprint-9c722.firebaseapp.com',
    storageBucket: 'study-sprint-9c722.appspot.com',
    measurementId: 'G-T26P968W33',
  );

}